//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRC_NET_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Assessment
    {
        public int AssessmentID { get; set; }
        public int MemberID { get; set; }
        public int AssessmentNameID { get; set; }
        public string AssessmentDesc { get; set; }
        public int ValueID { get; set; }
        public System.DateTime AssessmentDate { get; set; }
        public string AssessedBy { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime AddedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string BackgroundStory { get; set; }
        public string Fears { get; set; }
        public string AttitudeTowardUnion { get; set; }
        public string IDdLeaders { get; set; }
        public string FollowUp { get; set; }
    
        public virtual tb_AssessmentName tb_AssessmentName { get; set; }
        public virtual tb_AssessmentValue tb_AssessmentValue { get; set; }
        public virtual tb_MemberMaster tb_MemberMaster { get; set; }
    }
}
