//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRC_NET_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_AlsoWorksAt
    {
        public int AlsoWorksAtID { get; set; }
        public string Note { get; set; }
        public int EmployerID { get; set; }
        public int MemberID { get; set; }
        public Nullable<System.DateTime> AddedDateTime { get; set; }
        public Nullable<int> AddedBy { get; set; }
    
        public virtual tb_MemberMaster tb_MemberMaster { get; set; }
        public virtual tb_Employers tb_Employers { get; set; }
    }
}
