//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRC_NET_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Activity()
        {
            this.tb_MemberActivity = new HashSet<tb_MemberActivity>();
        }
    
        public int ActivityID { get; set; }
        public int ActivityStatusID { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public string ActivityName { get; set; }
        public string ActivityNote { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_MemberActivity> tb_MemberActivity { get; set; }
    }
}
