//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRC_NET_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Campus
    {
        public int CampusID { get; set; }
        public byte CollegeID { get; set; }
        public string CampusCode { get; set; }
        public string CampusName { get; set; }
    
        public virtual tb_College tb_College { get; set; }
    }
}
