//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRC_NET_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CampusMapping
    {
        public int ID { get; set; }
        public int CampusID { get; set; }
        public string MemberMappingCode { get; set; }
        public string ScheduleMappingName { get; set; }
    
        public virtual tb_Campus tb_Campus { get; set; }
    }
}
