//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRC_NET_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MemberActivity
    {
        public int MemberActivityID { get; set; }
        public int ActivityID { get; set; }
        public string ActivityStatus { get; set; }
        public Nullable<bool> Membership { get; set; }
        public Nullable<byte> MembershipCommitment { get; set; }
        public int MemberID { get; set; }
    
        public virtual tb_Activity tb_Activity { get; set; }
        public virtual tb_MemberMaster tb_MemberMaster { get; set; }
    }
}
