//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRC_NET_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MemberRoles
    {
        public int MemberRoleID { get; set; }
        public int MemberID { get; set; }
        public int BodyID { get; set; }
        public int RoleID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool Expired { get; set; }
    
        public virtual tb_Body tb_Body { get; set; }
        public virtual tb_MemberMaster tb_MemberMaster { get; set; }
        public virtual tb_Roles tb_Roles { get; set; }
    }
}
