//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRC_NET_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MemberSemester
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_MemberSemester()
        {
            this.tb_MemberSemesterCourse = new HashSet<tb_MemberSemesterCourse>();
        }
    
        public int MemberSemesterID { get; set; }
        public int MemberId { get; set; }
        public int SemesterId { get; set; }
        public int CollegeId { get; set; }
    
        public virtual tb_College tb_College { get; set; }
        public virtual tb_MemberMaster tb_MemberMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_MemberSemesterCourse> tb_MemberSemesterCourse { get; set; }
    }
}
