//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRC_NET_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Room
    {
        public int RoomID { get; set; }
        public string RoomName { get; set; }
        public Nullable<int> BuildingID { get; set; }
    
        public virtual tb_Building tb_Building { get; set; }
    }
}
