//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRC_NET_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SemesterTaught
    {
        public int SemesterTaughtID { get; set; }
        public int SemesterRecID { get; set; }
        public int MemberID { get; set; }
        public string Room { get; set; }
        public string Class { get; set; }
        public System.TimeSpan ClassStart { get; set; }
        public System.TimeSpan ClassEnd { get; set; }
        public int ClassWeekDayID { get; set; }
        public int BuildingID { get; set; }
        public bool ScheduleStatus { get; set; }
    
        public virtual tb_Building tb_Building { get; set; }
        public virtual tb_Semesters tb_Semesters { get; set; }
        public virtual tb_WeekDay tb_WeekDay { get; set; }
        public virtual tb_MemberMaster tb_MemberMaster { get; set; }
    }
}
