//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRC_NET_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Schedule_Error
    {
        public int ErrorId { get; set; }
        public Nullable<System.DateTime> ErrorDateTime { get; set; }
        public Nullable<int> RecordInCBU { get; set; }
        public string Id { get; set; }
        public string Instructor { get; set; }
        public string Campus { get; set; }
        public string Location { get; set; }
        public string Building { get; set; }
        public string Room { get; set; }
        public string Division { get; set; }
        public string ClassNumber { get; set; }
        public string CAT_NBR { get; set; }
        public string Sect { get; set; }
        public string Subject { get; set; }
        public string LecOrLab { get; set; }
        public string SB_TM { get; set; }
        public string ATT_TP { get; set; }
        public string BeginTime { get; set; }
        public string EndTime { get; set; }
        public string Days { get; set; }
        public string ClassEndDate { get; set; }
        public string Error { get; set; }
        public string Warning { get; set; }
    }
}
