//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRC_NET_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SemesterTaught
    {
        public int SemesterTaughtID { get; set; }
        public Nullable<int> SemesterRecID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public System.TimeSpan ClassStart { get; set; }
        public Nullable<System.TimeSpan> ClassEnd { get; set; }
        public Nullable<int> ClassWeekDayID { get; set; }
    
        public virtual tb_MemberMaster tb_MemberMaster { get; set; }
        public virtual tb_Semesters tb_Semesters { get; set; }
        public virtual tb_Class tb_Class { get; set; }
        public virtual tb_Room tb_Room { get; set; }
        public virtual tb_WeekDay tb_WeekDay { get; set; }
    }
}
