//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRC_NET_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Users
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public byte CredentialsID { get; set; }
        public Nullable<int> MemberID { get; set; }
    
        public virtual tb_UsersCredential tb_UsersCredential { get; set; }
        public virtual tb_MemberMaster tb_MemberMaster { get; set; }
    }
}
